version: "3"

services:
  signaler:
    build: ./signaler
    ports:
      - "5001:443"
    volumes:
     - ./signaler:/usr/local/src/github.com/pions/demo-conference/signaler
  turn:
    build: ./turn
    environment:
      - FQDN=localhost
    ports:
     - "3478:3478/udp"
    volumes:
     - ./turn:/usr/local/src/github.com/pions/demo-conference/turn
  www:
    build: ./www
    ports:
      - "5000:443"
    volumes:
     - ./www:/usr/local/src/github.com/pions/demo-conference/www
